<?php

return [
    'endpoint'  =>  env('LOCALIZA_API_ENDPOINT',"test"),
    'username'  =>  env('LOCALIZA_API_USERNAME',"test"),
    'password'  =>  env('LOCALIZA_API_PASSWORD',"test"),
    'token'  =>  env('LOCALIZA_API_TOKEN',"test"),
    'requestorID'  =>  env('LOCALIZA_API_REQUESTOR_ID',"test"),
    'reservationEmailAddress' => env('LOCALIZA_RESERVATION_EMAIL_ADDRESS',"test"),
    'bccEmailAddress' => env('LOCALIZA_RESERVATION_BCC_EMAIL_ADDRESS',"test"),
    'basicCoveragePriceLowGamma' => env('LOCALIZA_BASIC_COVERAGE_PRICE_LOW_GAMMA',29000),
    'basicCoveragePriceHighGamma' => env('LOCALIZA_BASIC_COVERAGE_PRICE_HIGH_GAMMA',49000),
    'totalCoveragePriceLowGamma' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_LOW_GAMMA',61085),
    'totalCoveragePriceHighGamma' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_HIGH_GAMMA',91016),

    'totalCoverageCategoryC' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_C',49859),
    'totalCoverageCategoryF' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_F',62002),
    'totalCoverageCategoryFX' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_FX',62002),
    'totalCoverageCategoryFL' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_FL',62002),
    'totalCoverageCategoryFU' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_FU',62002),
    'totalCoverageCategoryGC' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_GC',65110),
    'totalCoverageCategoryGL' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_GL',65110),
    'totalCoverageCategoryG4' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_G4',65110),
    'totalCoverageCategoryGR' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_GR',102011),
    'totalCoverageCategoryGY' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_GY',102011),
    'totalCoverageCategoryLE' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_LE',102011),
    'totalCoverageCategoryVP' => env('LOCALIZA_TOTAL_COVERAGE_PRICE_CATEGORY_VP',102011),

    'totalCoverageMonthCategoryC' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_C',49859),
    'totalCoverageMonthCategoryF' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_F',62002),
    'totalCoverageMonthCategoryFX' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_FX',62002),
    'totalCoverageMonthCategoryFL' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_FL',62002),
    'totalCoverageMonthCategoryFU' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_FU',62002),
    'totalCoverageMonthCategoryGC' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_GC',65110),
    'totalCoverageMonthCategoryGL' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_GL',65110),
    'totalCoverageMonthCategoryG4' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_G4',65110),
    'totalCoverageMonthCategoryGR' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_GR',102011),
    'totalCoverageMonthCategoryGY' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_GY',102011),
    'totalCoverageMonthCategoryLE' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_LE',102011),
    'totalCoverageMonthCategoryVP' => env('LOCALIZA_TOTAL_COVERAGE_MONTH_PRICE_CATEGORY_VP',102011),

    'ivaPercentage'             => env('LOCALIZA_IVA_PERCENTAGE',19),
    'taxFeePercentage'             => env('LOCALIZA_TAX_FEE_PERCENTAGE',10),
];
